---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    groups:
      github-actions:
        update-types:
          - minor
          - patch
    schedule:
      interval: monthly
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: monthly
    groups:
      pip:
        update-types:
          - minor
          - patch
