---
"":
  - type: A
    values:
      - 216.239.32.21
      - 216.239.34.21
      - 216.239.36.21
      - 216.239.38.21
    octodns:
      cloudflare:
        proxied: false
        auto-ttl: true
  - type: MX
    values:
      - exchange: aspmx.l.google.com.
        preference: 1
      - exchange: alt1.aspmx.l.google.com.
        preference: 5
      - exchange: alt2.aspmx.l.google.com.
        preference: 5
      - exchange: alt3.aspmx.l.google.com.
        preference: 10
      - exchange: alt4.aspmx.l.google.com.
        preference: 10
  - type: TXT
    values:
      - google-site-verification=12tsato1H6YJFtEbEP8gL1UDZjNEoTyc88JkZEjcKII
      - v=spf1 include:_spf.google.com -all
      - google-site-verification=1d_AcTbsWjApLpKHg6gWR9oqSLx8tixXGVqc00mXx8w

_github-challenge-caragolfoundation-org:
  octodns:
    cloudflare:
      auto-ttl: true
  ttl: 300
  type: TXT
  value: 7ad012b0ae

www:
  octodns:
    cloudflare:
      auto-ttl: true
      proxied: false
  ttl: 300
  type: CNAME
  value: ghs.googlehosted.com.
