---
? ''
: - octodns:
      cloudflare:
        proxied: true
        auto-ttl: true
    type: CNAME
    value: ghtrending.pages.dev
  - octodns:
      cloudflare:
        proxied: false
        auto-ttl: true
    type: MX
    values:
      - exchange: route3.mx.cloudflare.net
        preference: 5
      - exchange: route2.mx.cloudflare.net
        preference: 82
      - exchange: route1.mx.cloudflare.net
        preference: 95
  - octodns:
      cloudflare:
        proxied: false
        auto-ttl: true
    type: TXT
    values:
      - v=spf1 include:_spf.mx.cloudflare.net ~all
      - google-site-verification=MDJ0aMnhpJc7hbCnUs8z0jbizoNXorxW7Q13FenzOpU

ingest:
  octodns:
    cloudflare:
      proxied: false
      auto-ttl: true
  type: A
  value: 20.172.212.22

data:
  octodns:
    cloudflare:
      proxied: true
      auto-ttl: true
  type: CNAME
  value: data.ghtrending.io.s3-website-us-east-1.amazonaws.com
