---
"":
  type: A
  octodns:
    cloudflare:
      auto-ttl: true
  ttl: 300
  values:
    - 185.199.108.153
    - 185.199.109.153
    - 185.199.110.153
    - 185.199.111.153
www:
  ttl: 300
  type: CNAME
  value: gldnfloral.github.io.
  octodns:
    cloudflare:
      auto-ttl: true
