---
"":
  - type: MX
    octodns:
      cloudflare:
        auto-ttl: true
    ttl: 300
    values:
      - exchange: route1.mx.cloudflare.net.
        preference: 12
      - exchange: route3.mx.cloudflare.net.
        preference: 21
      - exchange: route2.mx.cloudflare.net.
        preference: 80
  - type: TXT
    octodns:
      cloudflare:
        auto-ttl: true
    ttl: 300
    value: v=spf1 include:_spf.mx.cloudflare.net ~all
_github-challenge-runwayapp-org:
  octodns:
    cloudflare:
      auto-ttl: true
  ttl: 300
  type: TXT
  value: 27dd55db51
api:
  octodns:
    cloudflare:
      auto-ttl: true
  ttl: 300
  type: CNAME
  value: air-traffic-control.azurewebsites.net.
app:
  octodns:
    cloudflare:
      auto-ttl: true
  ttl: 300
  type: CNAME
  value: runwayapp.azurewebsites.net.
asuid.api:
  octodns:
    cloudflare:
      auto-ttl: true
  ttl: 300
  type: TXT
  value: 966A35FCB4A0FE1176E2320038F9EA960F6E2FE36A69ABDFC79A272FE4E2228F
asuid.app:
  octodns:
    cloudflare:
      auto-ttl: true
  ttl: 300
  type: TXT
  value: 966A35FCB4A0FE1176E2320038F9EA960F6E2FE36A69ABDFC79A272FE4E2228F
