#!/usr/bin/env bash

set -euo pipefail

source script/env "$@"
cd "$DIR"

if [ ! -x "$VENV_DIR/bin/octodns-sync" ]; then
  script/bootstrap "$@"
fi

"$VENV_DIR/bin/octodns-sync" --version
"$VENV_DIR/bin/python" script/ci/test_update_deploy_msg.py
