name: noop

on:
  pull_request:
  workflow_dispatch:

jobs:
  noop:
    name: noop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - run: pip install -r requirements.txt

      - uses: solvaholic/octodns-sync@v3.0.1
        with:
          config_path: production.yaml
          doit: ""
          add_pr_comment: "Yes"
          pr_comment_token: ${{ github.token }}
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}

      - name: test
        run: echo ${{ github.event.pull_request.comments_url }}
