name: test
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: openai/fence@e6b39c80c51cb2b2a39448ddeff74b3b886c0a63 # pin@v0.10.0
        with:
          allowlist: |
            hostname pypi.org tcp 443
            hostname files.pythonhosted.org tcp 443

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # pin@v6
        with:
          persist-credentials: false

      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # pin@v6
        with:
          python-version-file: .python-version

      - name: bootstrap
        run: script/bootstrap

      - name: test
        run: script/test
