name: test
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: openai/fence@c22db5d5c19f83d1d7b40e9def37a7a6099bbca2 # pin@v0.8.10
        with:
          allowlist: |
            hostname pypi.org tcp 443
            hostname files.pythonhosted.org tcp 443

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # pin@v6
        with:
          persist-credentials: false

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # pin@v6
        with:
          python-version-file: .python-version

      - name: bootstrap
        run: script/bootstrap

      - name: test
        run: script/test
